DECLARE @directory NVARCHAR(max) = N'C:\ProjektZaliczeniowyDatabase';
DECLARE @db_name NVARCHAR(MAX) = N'Tracking';

DECLARE @db_filename NVARCHAR(MAX) = CONCAT(@directory, '\', @db_name, '.mdf')
DECLARE @db_log_name NVARCHAR(MAX) = CONCAT(@db_name, '_log')
DECLARE @db_log_filename NVARCHAR(MAX) = CONCAT(@directory, '\', @db_log_name, '.ldf')


USE [master]
DROP DATABASE IF EXISTS Tracking
/****** Object:  Database [Tracking]    Script Date: 18.03.2021 11:40:48 ******/
DECLARE @sql_db_create NVARCHAR(MAX) = N'
CREATE DATABASE [Tracking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'''+@db_name+''', FILENAME = N'''+@db_filename+''' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'''+@db_log_name+''', FILENAME = N'''+@db_log_filename+''' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
';
EXEC sp_executesql @sql_db_create


ALTER DATABASE [Tracking] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tracking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Tracking] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Tracking] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Tracking] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Tracking] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Tracking] SET ARITHABORT OFF 
GO
ALTER DATABASE [Tracking] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Tracking] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Tracking] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Tracking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Tracking] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Tracking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Tracking] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Tracking] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Tracking] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Tracking] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Tracking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Tracking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Tracking] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Tracking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Tracking] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Tracking] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Tracking] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Tracking] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Tracking] SET  MULTI_USER 
GO
ALTER DATABASE [Tracking] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Tracking] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Tracking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Tracking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Tracking] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Tracking] SET QUERY_STORE = OFF
GO
USE [Tracking]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Tracking]
GO
/****** Object:  Table [dbo].[EventType]    Script Date: 18.03.2021 12:23:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventType](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_EventType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrackingLogEvent]    Script Date: 18.03.2021 12:23:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrackingLogEvent](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[EventTypeId] [int] NOT NULL,
	[UserIPAddress] [varchar](15) NOT NULL,
	[CustomerId] [int] NULL,
	[UpdatePageUrl] [nvarchar](200) NULL,
 CONSTRAINT [PK_TrackingLogEvent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[EventType] ([Id], [Name]) VALUES (1, N'CustomerListVisited')
GO
INSERT [dbo].[EventType] ([Id], [Name]) VALUES (2, N'CustomerAdded')
GO
INSERT [dbo].[EventType] ([Id], [Name]) VALUES (3, N'CustomerUpdated')
GO
INSERT [dbo].[EventType] ([Id], [Name]) VALUES (4, N'CustomerDeleted')
GO
ALTER TABLE [dbo].[TrackingLogEvent]  WITH CHECK ADD  CONSTRAINT [FK_TrackingLogEvent_EventType] FOREIGN KEY([EventTypeId])
REFERENCES [dbo].[EventType] ([Id])
GO
ALTER TABLE [dbo].[TrackingLogEvent] CHECK CONSTRAINT [FK_TrackingLogEvent_EventType]
GO
USE [master]
GO
ALTER DATABASE [Tracking] SET  READ_WRITE 
GO
